In [1]:
import pandas as pd
columns=['Name', 'Features', 'Location', 'Price', "Seller", "Auction_Type", "Date"] 

d1 = pd.read_csv("data1.csv", names=columns, header=None)
d2 = pd.read_csv("data2.csv", names=columns, header=None)
d3 = pd.read_csv("data3.csv", names=columns, header=None)

In [2]:
frames = [d1, d2, d3]
result = pd.concat(frames)

In [3]:
result = result.drop_duplicates()
result.to_csv("Porsche.csv",index=False)

In [4]:

res = pd.read_csv("Porsche.csv", names=columns,header= None)

In [5]:
res

,Name,Features,Location,Price,Seller,Auction_Type,Date
0,Name,Features,Location,Price,Seller,Auction_Type,Date
1,2014 Porsche 911 Carrera S,"29,132 mi · Automatic · LHD · Original & Highl...","Bellevue, WA, USA",SOLD,Park Place LTD,Fixed-price,"Nov 27, 2022"
2,2002 Porsche 911 Carrera,"8,292 mi · Manual · LHD · Original & Highly Or...","Bellevue, WA, USA",SOLD,Park Place LTD,Fixed-price,"Nov 23, 2022"
3,2022 Porsche 911 GT3 Touring,133 mi · Manual · LHD · Original & Highly Orig...,"Elkhart Lake, WI, USA",SOLD,The Throttlestop,Fixed-price,"Nov 23, 2022"
4,2022 Porsche 911 Turbo,"1,863 mi · Automatic · LHD · Original & Highly...","Elkhart Lake, WI, USA",SOLD,The Throttlestop,Fixed-price,"Nov 23, 2022"
...,...,...,...,...,...,...,...
9917,1979 Porsche 930 3.3 Turbo Coupe,Manual,"Carmel, CA, USA","$162,400\nSOLD",Bonhams,Auction,"Aug 24, 2018"
9918,1991 Porsche 911 Carrera 4 Coupe,NaN,"Carmel, CA, USA","$156,800\nSOLD",Bonhams,Auction,"Aug 24, 2018"
9919,1996 Porsche 911 GT2 Club Sport,NaN,"Carmel, CA, USA","$1,105,000\nSOLD",Bonhams,Auction,"Aug 24, 2018"
9920,1996 Porsche 993 Turbo,Manual · LHD,"Carmel, CA, USA","$302,000\nSOLD",Bonhams,Auction,"Aug 24, 2018"
9921,1977 Porsche 930 3.0 Turbo Coupe,"5,000 mi · Manual","Carmel, CA, USA","$106,400\nSOLD",Bonhams,Auction,"Aug 24, 2018"